name: Workflow Name

on:
  push:
    branches: [main]

jobs:
  job-name: Test-Basic
    runs-on: [self hosted,Linux]
    
    steps:
      - name: test file
        run: echo "Hello Team"
